### ISSUE TITLE
Hitting RerollBoardField crashes game

### ISSUE THREAD

**Issue by TheForcer** [RAlbiez/SchnappsAndLiquor#16]
```
SchnappsAndLiquor | 08/17/2021 15:08:43|Fatal|<>c__DisplayClass174_0.<startReceiving>b__2:2186|WebSocketSharp.WebSocketException: The header part of a frame could not be read.
SchnappsAndLiquor |                              at WebSocketSharp.WebSocketFrame.processHeader(Byte[] header) in /app/wss/WebSocketFrame.cs:line 475
SchnappsAndLiquor |                              at WebSocketSharp.WebSocketFrame.<>c__DisplayClass73_0.<readHeaderAsync>b__0(Byte[] bytes) in /app/wss/WebSocketFrame.cs:line 593
SchnappsAndLiquor |                              at WebSocketSharp.Ext.<>c__DisplayClass57_0.<ReadBytesAsync>b__0(IAsyncResult ar) in /app/wss/Ext.cs:line 807SchnappsAndLiquor | 08/17/2021 15:08:43|Info |MasterServer.OnClientDisconnect:131|Closed game session TTZNKA (1        Games/2 Players)
```

**Comment by RAlbiez** [comment]
[https://stackoverflow.com/a/49645592](https://stackoverflow.com/a/49645592) maybe
